### PR TITLE
Created a list of projects and added the link to the README.

### LINKED ISSUE #30: Publish a list of security-related projects
# Description 
There are many great crates and projects out there that enhance or assess the security of the Rust ecosystem someway. However there is currently no central point from which these projects can be found and they are often linked through blog posts or interesting discussions on Zulip.

I think the README of this working group would be a great place to collect projects that can be of helping achieving our [2019 Working Group Goals](https://medium.com/@shnatsel/security-as-rust-2019-goal-6a060116ba39) (Kudo's for Shnatsel on writing this).

By doing this these projects would have more visibility and then can hopefully be used and improved to reach our goals.

I suggest that we leave this issue open for a week such that projects can be suggested. After that I can make a Pull Request that updates the README. Any projects that follow afterwards can then have a seperate PR.

### PR DESCRIPTION
**Pull request by DevQps**
# Description

- Added the list of projects mentioned by dfferent users in #30 
- Added a link to the README.

What do you guys think about this? I wasn't sure about the categories, so I highly suspect that some naming might be improved.

closes #30

### CODE REVIEW

**Comment by vakaras** [comment]
Does anyone see any reason why this should not be merged? If not, I would suggest merging this pull request.

**Comment by Shnatsel** [comment]
I'm sorry about the delay. I know how frustrating and demotivating long PR review times can be, and it's a shame I have inadvertedly caused that here :disappointed: 

The list looks good to me. However, I believe it would be better suited to a separate repository than a file under WG repo so that it can have a license, its own issue tracker, etc. So here's the course of action I propose:

1. Split the list into a new repository, under your name
1. Transfer the repository into the rust-secure-code organization
1. Strip this PR into just an addition of a link to README

Due to legal restrictions I cannot create new repositories personally. So if you can split this off into a repo I'll accept the ownership transfer on the WG organization and land this PR immediately afterwards.

And once again, apologies for the delay.

**Comment by DevQps** [comment]
@Shnatsel It says I can't transfer it because ```You don’t have the permission to create repositories on rust-secure-code```. Can you help me with this? The project I created is: https://github.com/DevQps/rustsec-projects

**Comment by Shnatsel** [comment]
That's weird, github docs do not mention anything like that. Perhaps you could transfer it to my account? I should have sufficient permissions to do pretty much anything with the org.

**Comment by DevQps** [comment]
Transfered it to you now!

**Comment by Shnatsel** [comment]
Aaand done! https://github.com/rust-secure-code/rustsec-projects

@DevQps you should still have direct commit access to it.

**Comment by DevQps** [comment]
Thanks man! I will edit this MR now.

**Comment by Shnatsel** [comment]
Merged. Thanks!

**Pull request merged**
